name: Build and Release plugin

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: gradle/wrapper-validation-action@v1
      
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build
          gradle-home-cache-cleanup: true
          
      - name: Upload artifacts (CI only)
        if: github.ref_type != 'tag' 
        uses: actions/upload-artifact@v4
        with:
          name: GeyserBlockPlatform
          path: |
            spigot/build/libs/GeyserBlockPlatform-Spigot.jar
            bungeecord/build/libs/GeyserBlockPlatform-Bungeecord.jar
            velocity/build/libs/GeyserBlockPlatform-Velocity.jar

      - name: Release .jar files (on tag)
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            spigot/build/libs/GeyserBlockPlatform-Spigot.jar
            bungeecord/build/libs/GeyserBlockPlatform-Bungeecord.jar
            velocity/build/libs/GeyserBlockPlatform-Velocity.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

